config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  resources :tasks
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :update, :edit, :destroy]
  def index
    #@tasks = Task.all.page(params[:page]).per(5)
    
    if logged_in?
      #@task = current_user.tasks.build  # form_for 用
      @tasks = current_user.tasks.page(params[:page])
    end
    
  end
  
  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    #@task = Task.new(task_params)
    
    @task = current_user.tasks.build(task_params)

    if @task.save
      flash[:success] = 'タスクが正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクが投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = 'タスクは正常に削除されました'
    redirect_to tasks_url
  end
  
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @tasks = current_user.tasks.page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to("/tasks")
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><img src="assets/task.ico"  width="30" height="30" class="d-inline-block align-top" alt="">TASK</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <% if logged_in? %>
      <%= link_to 'ログアウト', logout_path, method: :delete, :class=>"btn btn-sm btn-outline-light" %>
      <%= link_to 'タスク一覧', tasks_path, :class=>"btn btn-info" %>
      <%= link_to '新規タスクの投稿', new_task_path, :class=>"btn btn-primary" %>
      <% else %>
      
      
      <li class="nav-item">
        <%= link_to 'ログイン', login_path, :class=>"btn btn-sm  btn-outline-light" %>
        <%= link_to 'ユーザー登録が必要です', signup_path, :class=>"btn btn-sm  btn-outline-light" %>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Tasklist</title>
  
  <%= csrf_meta_tags %>
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
  <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    
    
  </div>  <!---------^^^CONTAINER^^^------------>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  
  
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2 col-lg-6 offset-lg-3">
  <%= form_for(task) do |f| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
      <div class="alert alert-warning">
        <ul>
          <% task.errors.full_messages.each do |task| %>
            <li><%= task %></li>
          <% end %>
        </ul>
      </div>
      </div>
    <% end %>
    
    <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
    </div>
  
    <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
    </div>
  
    <%= f.submit '投稿', class: 'btn btn-primary' %>
  
  <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>☆タスク一覧☆</h1>

<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タスク</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @tasks %>
  </div>
<% end %>
  
  <%= link_to '新規タスクの投稿', new_task_path, class: "btn btn-primary" %>
  
  

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id= <%= @task.id %> のタスク詳細ページ</h1>

<table class="table table-bordered">
    <tr>
        <th>id</th>
        <td>
            <%= @task.id %>
        </td>
    </tr>
    <tr>
        <th>タスク</th>
        <td>
            <%= @task.content %>
        </td>
    </tr>
    <tr>
        <th>ステータス</th>
        <td>
            <%= @task.status %>
        </td>
    </tr>
</table>



<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-default' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p><%= current_user.name %>さん、ログイン中</p>



<h1>☆タスク一覧☆</h1>

<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タスク</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @tasks %>
  </div>
<% end %>
  
  <%= link_to '新規タスクの投稿', new_task_path, class: "btn btn-primary" %>
  






  
  
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>TASK LIST へようこそ</h1>
      <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>